services:
  gaze_detector_node:
    build: .
    container_name: ros2_gaze_container
    # Mounts your current Mac directory to the container workspace.
    # This means any changes you make to your python code instantly sync!
    volumes:
      - .:/ros2_ws
      - /ros2_ws/__pycache__
    working_dir: /ros2_ws
    # Map port 5050 on your Mac to port 5050 inside the Docker container
    ports:
      - "5050:5050"
    # Restart the container automatically if it encounters an error
    restart: unless-stopped